// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entities "scheduler/internal/domain/entities"
	task "scheduler/internal/usecases/task"
	time "time"

	cron "github.com/robfig/cron/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
	isgomock struct{}
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockTaskService) Complete(ctx context.Context, taskIDStr, workerIDStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, taskIDStr, workerIDStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockTaskServiceMockRecorder) Complete(ctx, taskIDStr, workerIDStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockTaskService)(nil).Complete), ctx, taskIDStr, workerIDStr)
}

// Create mocks base method.
func (m *MockTaskService) Create(ctx context.Context, dto task.CreateDto) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dto)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskServiceMockRecorder) Create(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskService)(nil).Create), ctx, dto)
}

// Fail mocks base method.
func (m *MockTaskService) Fail(ctx context.Context, taskIDStr, workerIDStr, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fail", ctx, taskIDStr, workerIDStr, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fail indicates an expected call of Fail.
func (mr *MockTaskServiceMockRecorder) Fail(ctx, taskIDStr, workerIDStr, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockTaskService)(nil).Fail), ctx, taskIDStr, workerIDStr, errorMsg)
}

// Get mocks base method.
func (m *MockTaskService) Get(ctx context.Context, idStr string) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, idStr)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskServiceMockRecorder) Get(ctx, idStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskService)(nil).Get), ctx, idStr)
}

// Heartbeat mocks base method.
func (m *MockTaskService) Heartbeat(ctx context.Context, taskIDStr, workerIDStr string, extend time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, taskIDStr, workerIDStr, extend)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockTaskServiceMockRecorder) Heartbeat(ctx, taskIDStr, workerIDStr, extend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockTaskService)(nil).Heartbeat), ctx, taskIDStr, workerIDStr, extend)
}

// List mocks base method.
func (m *MockTaskService) List(ctx context.Context, limit, offset int) ([]entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskServiceMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskService)(nil).List), ctx, limit, offset)
}

// Poll mocks base method.
func (m *MockTaskService) Poll(ctx context.Context, queueName, workerIDStr string) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", ctx, queueName, workerIDStr)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockTaskServiceMockRecorder) Poll(ctx, queueName, workerIDStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockTaskService)(nil).Poll), ctx, queueName, workerIDStr)
}

// MockCronParser is a mock of CronParser interface.
type MockCronParser struct {
	ctrl     *gomock.Controller
	recorder *MockCronParserMockRecorder
	isgomock struct{}
}

// MockCronParserMockRecorder is the mock recorder for MockCronParser.
type MockCronParserMockRecorder struct {
	mock *MockCronParser
}

// NewMockCronParser creates a new mock instance.
func NewMockCronParser(ctrl *gomock.Controller) *MockCronParser {
	mock := &MockCronParser{ctrl: ctrl}
	mock.recorder = &MockCronParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCronParser) EXPECT() *MockCronParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockCronParser) Parse(expr string) (cron.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", expr)
	ret0, _ := ret[0].(cron.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCronParserMockRecorder) Parse(expr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCronParser)(nil).Parse), expr)
}
