// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v3 "github.com/robfig/cron/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockCronParser is a mock of CronParser interface.
type MockCronParser struct {
	ctrl     *gomock.Controller
	recorder *MockCronParserMockRecorder
	isgomock struct{}
}

// MockCronParserMockRecorder is the mock recorder for MockCronParser.
type MockCronParserMockRecorder struct {
	mock *MockCronParser
}

// NewMockCronParser creates a new mock instance.
func NewMockCronParser(ctrl *gomock.Controller) *MockCronParser {
	mock := &MockCronParser{ctrl: ctrl}
	mock.recorder = &MockCronParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCronParser) EXPECT() *MockCronParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockCronParser) Parse(expr string) (v3.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", expr)
	ret0, _ := ret[0].(v3.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCronParserMockRecorder) Parse(expr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCronParser)(nil).Parse), expr)
}
